import Sidebar from "@/components/navigation/sidebar";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Racetrack Admin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <body className="flex">
        <Sidebar/>
        {children}
    </body>
  );
}