import Sidebar from "@/components/navigation/sidebar";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Racetrack Admin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <body className="flex min-h-screen">
        
        <div className="w-72 min-h-full flex-shrink-0">
        <Sidebar/>
        </div>

        <div className="flex-1 overflow-auto">
        {children}
        </div>
    </body>
  );
}