---
services:
  racetrack:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_ID: ${DEV_USER_ID}
        GROUP_ID: ${DEV_GROUP_ID}
        USERNAME: ${DEV_USERNAME}
        USER_PASSWORD: ${DEV_USER_PASSWORD}
    pull_policy: always
    volumes:
      - ..:/workspace:cached
    ports:
      - 3005:3005
      - 2222:22
  valkey:
    image: valkey/valkey:latest
    container_name: valkey
    restart: unless-stopped
    volumes:
      - ./valkey/valkey.conf:/etc/valkey/valkey.conf:ro
    ports:
      - "6379:6379"
    command: ["valkey-server", "/etc/valkey/valkey.conf"]